/* ───────────────────────────────────────────────────────────────────────────
   RÜZGÂR POSTASI — Her gün Eln'e bir not.
   Her gün (Bakü saatiyle) sıradaki not gösterilir; özel günlerde (ayın 21'i,
   ayın 6'sı, doğum günü, Novruz…) aşağıdaki özel notlar devreye girer.
   İstediğin kadar not ekleyebilirsin — sadece listeye yeni bir satır yaz.
   ─────────────────────────────────────────────────────────────────────────── */

export const NOTLAR: string[] = [
  'Bugün güneş yine önce sana uğradı. Kıskanmıyorum; ben güneş olsam ben de öyle yapardım.',
  'Sen benden hep bir saat ileridesin. Yani geleceğimde sen varsın; bu kesin.',
  'Bir gün “nerelisin?” diye sorduklarında “İstanbul” demeyeceğim. “Eln’in yanı” diyeceğim.',
  '1.758 km. Bir uçak için üç saat. Bir mesaj için altı milisaniye. Benim için sadece bir “günaydın” kadar.',
  'Gülüşünü düşününce ben de gülüyorum. Hem de otobüste, yabancıların önünde. Sorumlusu sensin.',
  'Hazar kıyısında rüzgâr saçlarını dağıtırsa bil ki o rüzgârı ben gönderdim. (Xəzri’yle aram iyi.)',
  'Seni hiç görmeden tanıdım. Yani seni gördüğüm gün, tanıdığım birini ilk kez görmüş olacağım. Böyle bir şey başka kimin başına gelir?',
  'Bugünün notu kısa: Səni sevirəm. Dünkü de buydu aslında. Yarınki de bu olacak.',
  'Bir gün aynı masada çay içeceğiz. Sonra bardakları değiştireceğiz: sen ince belliyi, ben armuduyu deneyeceğim.',
  'Ekranda adını görünce kalbim hâlâ ilk günkü gibi zıplıyor. “Alışsana artık” diyorum; dinlemiyor.',
  'Uzak mesafe diyorlar. Bence yanlış isim. Biz “her gün yeniden seçmek” ilişkisiyiz.',
  'Sana her “iyi geceler” dediğimde aslında “yarın yine buradayım” diyorum.',
  'Nehir’e hâlâ doğru düzgün teşekkür etmedim galiba. Hayatımın en güzel “gruba ekle” tuşuna o bastı.',
  'Senin “darıxmışam”ın benim “özledim”imden daha güzel. Ama ikisi de aynı yere çıkıyor: sana.',
  'Bakü’ye “rüzgârlar şehri” diyorlarmış. Beni uçuran rüzgârın nereden estiği belli oldu.',
  'Seni düşünmediğim bir saat bulmaya çalıştım. Bulamadım. Pes ettim. Çok mutluyum.',
  'Bir gün bir geliş kapısının önünde titreyen ellerle bekleyeceğim. O güne kadar her şey sadece prova.',
  'Mesajlarının yazılış biçimini ezberledim; hangi cümlenin sonuna ☺️ koyacağını bile. Sıra sesini ezberlemekte.',
  'Ay’a baktığında unutma: 1.758 km ötede biri de aynı aya bakıyor. Çoğu gece bakıyorum.',
  'Gözəlim. Bu kelimeyi senden öğrendim; artık başka kimseye yakışmıyor.',
  'Bazen hiçbir şey yazmadan sadece sohbetimize bakıyorum. En sevdiğim kitap o.',
  'Bugün seni biraz daha çok seviyorum. Bunu her gün söylüyorum ama her gün doğru.',
  'Sabah telefonumu açınca senden gelen ilk mesaj… Günüm tam oradan başlıyor.',
  'Ellerini hiç tutmadım. Ama biliyorum, sıcak olacaklar. Çünkü mesajların bile sıcak.',
  'Haritada aramızda Karadeniz, Kafkaslar ve koca bir Gürcistan var. Kalbimde aramızda hiçbir şey yok.',
  'Bir gün sana İstanbul’u gezdireceğim. Ama itiraf edeyim: manzaraya değil, sana bakacağım.',
  'Bir gün de sen bana Bakü’yü gezdir. Bulvarda yürüyelim, Hazar’a bakalım. Ben yine sana bakacağım. Kusura bakma.',
  'Bazı insanlar hayatına girer, bazıları hayatın olur. Sen ikincisisin. Hem de bir grup sohbetinden.',
  'Seninle konuşurken yüzümde bir gülümseme donup kalıyor. Aynaya bakmadan biliyorum.',
  'Mesafe bize sabrı öğretti. Sabır da bana şunu öğretti: seni beklemek bile güzel.',
  'Her gece uyumadan önce son düşündüğüm şey sensin. Her sabah da ilk. Arada rüyalar var; onlarda da sen.',
  'Bir saatlik fark bazen işime geliyor: sen uyuduktan sonra da bir saat boyunca sana “iyi geceler” diyebiliyorum.',
  'İki şehir, iki kule, iki bardak, iki dil. Ama tek bir kalp: bizimki.',
  'Hayalimde ilk buluşmamızın yüz farklı versiyonu var. Hepsi sarılarak bitiyor. Gerisi değişiyor.',
  'Birine seni anlatmaya kalksam gülümsemeden anlatamam. Denedim; olmadı.',
  '“Tezliklə” kelimesini senden öğrendim: yakında. Artık iki dilde de en sevdiğim kelime.',
  '“Gecən xeyrə qalsın.” Gecen hayra kalsın. Bir iyi geceler bu kadar güzel olabilir mi?',
  'Bu siteyi yaparken her satırda seni düşündüm. Yani bu site aslında çok uzun bir “seni düşünüyorum” mesajı.',
  'Beni hiç görmeden sevdin. Bunun ne kadar büyük bir şey olduğunu her gün biraz daha anlıyorum.',
  'Bugün kendine iyi bak: su iç, bir şeyler ye, biraz dinlen. Bu bir rica değil, sevgilinden resmî talimat.',
  'Moralin bozuksa bil ki 1.758 km ötede biri seni sadece var olduğun için seviyor. Hiçbir şey yapmana gerek yok.',
  'Seninle ilgili en sevdiğim şeylerden biri: kendin olman. Bir de ☺️’lerin. Bir de… liste uzun, notun yeri yetmez.',
  'Dünyanın çevresi 40.075 km. Aramızdaki mesafe bunun sadece %4’ü. Hesap yaptım: çok yakınız.',
  'Işık aramızdaki mesafeyi altı milisaniyede geçiyor. Ben de o kadar hızlı özlüyorum.',
  'Her ayın 21’i benim için küçük bir bayram. Her 6’sı da küçük bir teşekkür günü.',
  '“Nasıl tanıştınız?” diye sorduklarında “bir Nehir sayesinde” diyeceğiz. Herkes romantik bir hikâye sanacak. Haklı olacaklar.',
  'Sevgimiz demli çay gibi: bekledikçe koyulaşıyor.',
  'Seni ilk kez görünce ne yapacağımı bilmiyorum. Muhtemelen salak salak gülümseyeceğim. Şimdiden özür dilerim.',
  'Sen benim en güzel bildirimimsin.',
  'Ay bu gece de ikimizin. Paylaştığımız en güzel şeylerden biri.',
  'İstanbul kalabalık bir şehir. Ama sensiz bazen çok boş.',
  'Bakü’nün Alev Kuleleri gibisin: uzaktan bile görünüyorsun, uzaktan bile ısıtıyorsun.',
  'Bir gün seninle hiçbir şey yapmadan bir gün geçirmek istiyorum. Aynı odada, sadece yan yana. Bu bile yeter.',
  'Bazen ekrana dokunuyorum, sanki sana dokunuyormuşum gibi. Gülme. (Gül aslında. Gülüşünü seviyorum.)',
  'Sen uyuduğunda benim burada bir saatim daha oluyor. O bir saat boyunca rüyalarını korumakla görevliyim.',
  'Senin şehrinde bir Kız Kulesi var, benimkinde de. Dünya bize ipucu vermiş aslında.',
  'Hayatımda ilk kez biri için bir saat dilimi ezberledim: UTC+4.',
  '“Keşke yanında olsam” demiyorum artık. “Az qaldı” diyorum. Az kaldı.',
  'Bir gün sana simit alacağım, sen bana mürəbbə vereceksin. Kültürel değişim programımız başlasın.',
  'Yeni güne, yeni yıla, her şeye benden bir saat önce giriyorsun. Ben de hep arkandan, gülerek geliyorum.',
  'Bazı günler yorgun oluyorum. Sonra adın ekranda beliriyor ve yorgunluk sebepsiz yere geçiyor. Bilim bunu açıklayamıyor.',
  'Seni sevmek kolay. Zor olan, seni bu kadar uzaktan bu kadar çok sevmek. Ama sen olunca zoru da seviyorum.',
  'Seni beklemiyorum; seninle birlikte bekliyoruz. Aynı şey değil. İkincisi çok daha güzel.',
  'Bir gün bu siteyi yan yana açıp güleceğiz: “Uzaktayken ne kadar romantikmişiz.” Sonra yine romantik olacağız.',
  'Uzak mesafe bir sınav değil, bir hikâye. Ve en güzel bölümü daha yazılmadı.',
  'Sen benim günaydınımsın. Her iki dilde de.',
  'Səni sevirəm. Seni seviyorum. İki dilde de aynı ağırlıkta, aynı sıcaklıkta.',
  'Bugün sokakta bir kız armudu bardakla çay içiyordu. Hayır, uydurdum. Ama öyle olsaydı yine seni düşünürdüm.',
  'Galata’da gün batımını izleyeceğiz. Ben sana güneşi göstereceğim, sen de “bu güneş önce bana doğdu” diyeceksin. Haklı olacaksın.',
  'Seninle tanıştığımda kış başıydı. Sen olunca her mevsim biraz bahar gibi geçiyor. Klişe ama doğru.',
  'Bu notu okuyorsan bugün de beni hatırladın demektir. Teşekkür ederim. Ben seni zaten tek saniye unutmadım.',
  'Bir gün “uzak mesafe” kelimesini birlikte emekliye ayıracağız. Veda partisi de yaparız.',
  'Bir dakikalığına gözlerini kapat ve beni düşün. Tam o dakika ben de seni düşünüyor olacağım. Nereden mi biliyorum? Hep düşünüyorum.',
  'Ekran ışığı bizim kule lambamız. Her gece yanıyor, hiç sönmüyor.',
  'İyi ki varsın. Ve iyi ki o gruptaydın.',
  'En güzel tesadüf: seninle aynı enlemde yaşamak. En güzel karar: seninle olmak.',
  'Kalbimin bir şubesi Bakü’de. Hatta genel müdürlük orada.',
  'Seni görmeden sevmek, bir şarkıyı sözlerini bilmeden sevmek gibi. Sözleri öğrenince daha çok seversin. Ben o güne hazırım.',
  'Bugün sevdiğin bir şey ye, sevdiğin bir şarkıyı aç. Ve bil ki birisi seni en çok seviyor.',
  'Hiç buluşmadık ama seninle en çok yerde bulunmuş kişi benim: rüyalarımda, hayallerimde, planlarımda.',
  'Bakü ile İstanbul arasında direkt uçuş var. Bu, bildiğim en güzel bilgi.',
  '“İyi misin?” diye sorduğumda aslında “sen iyiysen ben de iyiyim” demek istiyorum.',
  'Sana olan sevgim bir ilk mesaj gibi: heyecanlı, biraz ürkek, çok samimi. Her gün yeniden.',
  'Senin gökyüzünde güneş batınca benimkinde hâlâ bir saatlik ışık kalıyor. O ışığı sana saklıyorum.',
  'Bir sabah uyandığında yanında olmak istiyorum. Günaydını yazmadan, söylemek için.',
  'Aramızdaki en güzel şey: hiçbir şeyin zorunlu olmaması ama her şeyin seçilmesi.',
  'Hazar ile Boğaz’ı nehirler birbirine bağlıyor. Bizi de bir Nehir bağladı. Bazen coğrafya bile romantik.',
  'Mesajlarının arasına koyduğun o küçük şeyleri bile özlüyorum; daha beş dakika önce yazmışken.',
  '“Canım” demek istedim. Güzel yanı: bu kelime iki dilde de aynı. Canım.',
  'İlk buluşmamızda saat farkı olmayacak. Aynı saat, aynı dakika, aynı yer. Düşünmesi bile başımı döndürüyor.',
  'Bu mesafe geçici. Sen kalıcısın.',
  'Her konuşmamız bir pencere: Bakü’den İstanbul’a açılan.',
  'Benim şehrim iki kıtaya yayılmış ama bende tek bir yön var: doğu. Sen oradasın.',
  'Bir gün bu notların hepsini sana yüksek sesle okuyacağım. Utançtan ölmezsem.',
  'Seni sevmenin en güzel yanı ne biliyor musun? Hiç bitmeyecek olması.',
  'Bugün de seni seçiyorum. Yarın da seçeceğim. Bu bir söz.',
  'Mənim günəşim. Güneş önce sana doğar; ben de önce sana.',
  'Bir gün Hazar’ın dalgalarını yanında dinleyeceğim. O zaman bu site sadece güzel bir hatıra olacak.',
  'Seni tanıdığımdan beri zaman farklı akıyor: günler kısa, özlem uzun.',
  '“Neden bu kadar mutlusun?” diye sorsalar cevabım tek kelime: Eln.',
  'Uzakta olman seni daha az sevmeme yol açmıyor. Aksine, seni sevmeye daha çok vakit ayırıyorum.',
  'Bir gün birlikte bir fotoğraf çekeceğiz; ekran görüntüsü değil, gerçek bir fotoğraf. Onu çerçeveleyeceğim.',
  'Evrende milyarlarca yıldız var. Ben bir tanesini buldum: Bakü’de yaşıyor.',
  'Az qaldı, gözəlim. Az qaldı.',
  'Günaydın {hitap}. Bugün de ilk düşündüğüm sensin; bu artık bir alışkanlık değil, bir kural.',
  'Adının içinde bir nar saklı, {tamAd}. Her söylediğimde ağzıma tatlı bir şey değiyor gibi.',
  '“Anılar”ı her dinlediğimde aklıma henüz yaşamadığımız anılar geliyor. Hepsi çok güzel, hepsinde sen varsın.',
  'Sana “{hitap}” dediğimde sesim kendiliğinden yumuşuyor. Denedim, sert söyleyemiyorum.',
  'Bir gün Hazar kıyısında sana nar soyacağım. Tanelerini tek tek sayacağım; her biri bir günümüz olacak.',
  'Bugün de gülümse {hitap}. Bin yedi yüz elli sekiz kilometre öteden görünüyor, emin ol.',
  'Senin için yazdığım bu satırlar bitecek ama sana söyleyeceklerim bitmeyecek.',
  'Bazen sadece adını yazıp siliyorum: {tamAd}. Sonra yine yazıyorum. Klavye bile seni seviyor artık.',
  '{hitap}, bugün bir şey fark ettim: seni özlemek bile seni sevmenin bir biçimi.',
  'Bu sitenin hiçbir yerinde “bok” kelimesi geçmiyor. Bu cümle hariç. ☺️',
  'Bana “posi” dediğinde adım bile değişiyor; Arda gidiyor, daha mutlu biri geliyor.',
  '“Mosi”, “şirinim”, “kuzum”… Bana taktığın her ad, telefonumda bir bayram.',
  'Pembe senin rengin. Bu sitede ne kadar pembe varsa, hepsini sana bakarak seçtim.',
  'Bir gün kapını çalacağım, elimde pembe zambaklarla. Kokusu merdivenlere kadar gelecek.',
  'Zambaklar sabırlı çiçeklerdir; tomurcuk uzun bekler, sonra bir sabah birden açar. Biz de öyleyiz.',
  'Bugünün notu tek kelime, bizim kelimemiz: öptüm.',
  'Sesli aramalarda utanıyoruz, mesajlarda susmuyoruz. Buluştuğumuzda hangisi olacak, çok merak ediyorum.',
  'Bugün bok gibi geçtiyse bana yaz. Bir ☺️ gönder, gerisini ben hallederim.',
  'Senin bir ☺️’ün, benim bütün günümü düzeltmeye yetiyor. Bilimsel olarak kanıtlandı. (Ben kanıtladım.)',
  'Sana bir sır: ☺️ attığın her seferinde ekrana bakıp aynı yüzü ben de yapıyorum.',
  'Hiç görüntülü konuşmadık. Ama gülüşünü mesajlarından o kadar iyi tanıyorum ki, ilk gördüğümde “işte o” diyeceğim.',
  'Sesli aramalarda ikimiz de biraz utangacız, biliyorum. Ama kapatırken dediğimiz o “öptüm”… O tek kelime her şeye değiyor.',
]

/* Özel günler. {n} = kaçıncı ay/yıl, {ad} = senin adın, {tamAd} = tam adın, {hitap} = rastgele bir hitap, {yas} = yaşın. */
export const OZEL_NOTLAR = {
  ayin21i:
    'Bugün ayın 21’i: bizim {n}. ayımız. {n} ay önce bugün “biz” olduk. Her 21’inde seni biraz daha çok seviyorum; bu ay da istisna değil.',
  ayin6si:
    '{n} ay önce bugün tanıştık. Nehir bir tuşa bastı, benim bütün hayatım değişti. İyi ki o gruptaydın.',
  yildonumuSevgili:
    'Bugün {n}. yılımız, {ad}. Bir yıl önce bugün hayatımın en güzel “evet”ini duydum. Her yıl yeniden: seni seçiyorum.',
  yildonumuTanisma:
    '{n} yıl önce bugün, bir gruba eklendim ve seni buldum. Bir yıl önce bilmiyordum; şimdi biliyorum: o gün hayatımın başladığı gündü.',
  sevgililerGunu: 'Sevgililer Günü. Biz her gün sevgiliyiz ama bugün bunu bütün dünya da kabul ediyor.',
  novruz:
    'Novruz bayramın mübarək, gözəlim! Baharın ilk günü. Tonqalın üstünden atlarken bir dilek tut. Benimki belli.',
  kadinlarGunu: '8 Mart. Dünyanın en güzel, en güçlü, en sevilen kadınına: iyi ki varsın. İyi ki benimsin.',
  yeniYil:
    'Yeni yıla yine benden bir saat önce girdin. Bu yılki dileğim: saat farkımızın sıfırlandığı bir gece.',
  dogumGunuSen:
    'İyi ki doğdun {tamAd}! {yas} yaşın kutlu olsun, ad günün mübarək! 23 Nisan’da doğmuşsun: bizde bugün bayram, bütün ülke bayrak asıyor. Bence hepsi senin için. Bu yıl uzaktan kutluyorum; bir dahakine pastayı ben keseceğim, mumlarını yanında üfleyeceksin.',
  dogumGunuBen:
    'Bugün benim doğum günüm ama hediyeyi çoktan aldım: seni. Başka bir şey istemiyorum. (Belki bir mesaj. Uzun bir tane. Rüzgâra bırakırsan bana gelir.)',
}

/* ───────────────────────────────────────────────────────────────────────────
   GÜNÜN SORUSU — Rüzgâr Postası'nda her gün bir soru. Eln cevaplarsa cevap,
   soruyla birlikte telefonuna düşer. Sesli aramada söyleyemediklerimiz için.
   ─────────────────────────────────────────────────────────────────────────── */
export const SORULAR: string[] = [
  'Buluştuğumuzda ilk ne yemek istersin?',
  'Beni ilk gördüğünde ne diyeceksin? (Hiçbir şey diyemeyeceksin, biliyorum.)',
  'Bugün seni en çok ne güldürdü?',
  'O grupta benimle ilgili ilk neyi fark etmiştin?',
  'Hangi şarkıyı dinlerken aklına ben geliyorum?',
  'Bakü’de bana ilk göstereceğin yer neresi?',
  'İstanbul’da bir günün olsa, nereye gitmek isterdin?',
  'Beni üç kelimeyle anlat.',
  'Bende en sevdiğin huy hangisi? Sadece bir tane seç. (Zor, biliyorum.)',
  'Şu an yanına bir şey getirebilsem, ne olsun?',
  'Hayalindeki bir pazar günü nasıl geçer?',
  'Birlikte izlediğimiz ilk film ne olsun?',
  'Hangi mesajımı hâlâ hatırlıyorsun?',
  'Uyumadan önce aklından geçen son şey genelde ne oluyor?',
  'Kötü bir günde seni en çok ne rahatlatır?',
  'Beş yıl sonra bir sabah: neredeyiz, ne yapıyoruz?',
  'Bugün neye minnettarsın?',
  'Bana daha önce hiç söylemediğin küçük bir şey anlat.',
  'Sesli aramalarda neden bu kadar utanıyoruz sence? ☺️',
  'İlk görüntülü aramamız ne zaman olsun? (Tarih ver. Ciddiyim.)',
  'Posi mi, mosi mi, kuzum mu: bugün ben hangisiyim?',
  'Hangi mevsimde buluşmak isterdin?',
  'Bana bugün bir Azerbaycanca kelime öğret.',
  'Benim için bir şarkı seçsen, hangisi olurdu?',
  'En utanç verici anını anlat. Ben de kendiminkini anlatacağım, söz.',
  'Işınlanabilseydin şu an ilk nereye giderdin? (Cevabı biliyorum ama yine de yaz.)',
  'Nehir’e teşekkür olarak ne ısmarlamalıyız?',
  'Şimdiye kadar “biz”de en sevdiğin an hangisi?',
  'Bende en komik bulduğun şey ne?',
  'Birlikte bir yere gitsek: deniz mi, dağ mı, şehir mi?',
  'Sabah insanı mısın, gece mi? (Tahminim var.)',
  'Hangi konuda her zaman haklısın? ☺️',
  'Bugün kendin için güzel bir şey yaptın mı?',
  'Aşk senin için ne demek? Tek cümleyle.',
  'Bir gün evimiz olsa, en çok hangi odasında vakit geçirirdin?',
  'Havalimanında beni karşılarken elinde ne olsun?',
  'Bana henüz atmadığın bir fotoğrafın var mı? (Varsa at.)',
  'Seni en çok ne sinirlendirir? Not alıyorum.',
  'Rüyanda beni hiç gördün mü? Ne yapıyorduk?',
  'Bu sitede en sevdiğin yer neresi?',
  'Bugün “bok gibi” miydi, “çok güzel” mi? Hangisi, neden?',
  'Çocukken ne olmak istiyordun?',
  'En sevdiğin koku hangisi?',
  'Benim hakkımda hâlâ merak ettiğin bir şey var mı?',
  'Beni hangi hayvana benzetiyorsun? (Kuzum deme, çok kolay.)',
  'Birlikte pişireceğimiz ilk yemek ne olsun?',
  'Zambakları seviyorsun; peki neden? İlk ne zaman sevdin?',
  'Pembe dışında bir renk seçmek zorunda olsan?',
  'Seninle ilgili bilmemi istediğin, ama hiç sormadığım bir şey?',
  'İlk buluşmamız bir film sahnesi olsa, arkada hangi şarkı çalar?',
  'En çok hangi “öptüm”ü hatırlıyorsun?',
  'Bugün beni kaç kez düşündün? (Yuvarlak rakam verme.)',
  'Birbirimize mektup yazsak, ilk cümlen ne olurdu?',
  'Seni tanımayan birine beni nasıl anlatırsın?',
  'Bir gün boyunca rolleri değişsek, ilk ne yapardın?',
  'Bende değiştirmek istediğin bir şey var mı? Dürüst ol, kızmam. (Belki biraz.)',
]
